% guidedefaults.m - run this to set up nice
% defaults for publishing the "guide" series.
%
% LNT 2007

%'defaultfigureposition',[380 320 800 500],...

set(0,...
    'defaultfigureunits','inches',...
'defaultfigureposition',[1 1 6 2.5],...
'defaultfigurepaperposition',[0 0 6 2.5],...
'defaultaxeslinewidth',1,...
'defaultaxesfontsize',10,...
'defaultlinelinewidth',1.75,...
'defaultpatchlinewidth',1.5,...
'defaultlinemarkersize',16)
rand('state',sum(100*clock))
randn('state',2)
format compact, format long
chebfunpref.setDefaults('factory')