% guidedefaults.m - run this to set up nice
% defaults for publishing the "guide" series.
%
% LNT 2007

set(0,...
'defaultfigureposition',[380 320 540 200],...
'defaultaxeslinewidth',1.4,...
'defaultaxesfontsize',10,...
'defaultlinelinewidth',1.4,...
'defaultpatchlinewidth',1.4,...
'defaultlinemarkersize',16)
rand('state',sum(100*clock))
randn('state',2)
format compact, format long
