% guidedefaults.m - run this to set up nice
% defaults for publishing the "guide" series.
%
% LNT 2007

%'defaultfigureposition',[380 320 800 500],...

set(0,...
    'defaultfigureunits','inches',...
'defaultfigureposition',[1 1 5.5 2.3],...
'defaultfigurepaperposition',[0 0 5.5 2.3],...
'defaultaxeslinewidth',0.75,...
'defaultaxesfontsize',10,...
'defaultlinelinewidth',1.4,...
'defaultpatchlinewidth',1,...
'defaultlinemarkersize',12)
rand('state',sum(100*clock))
randn('state',2)
format compact, format long
chebfunpref.setDefaults('factory')